### ISSUE TITLE
Unable Undo

### ISSUE THREAD

**Issue by sheenli** [alelievr/NodeGraphProcessor#38] opened 2020-01-06 11:10 UTC
Unable Undo

**Comment by alelievr** [comment] 2020-01-06 13:05
Hello, which action are you unable to undo ?

**Comment by sheenli** [comment] 2020-01-06 13:08
delete  node

**Comment by alelievr** [comment] 2020-07-25 10:37
The issue is fixed in 014dfd75527bf893fd7dd97ed892732ef22a0dfe.

Thanks for the bug report

**Closed by alelievr** 2020-07-25 10:37 UTC
