### ISSUE TITLE
Provide values/literals directly next to the port

### ISSUE THREAD

**Issue by JefferiesTube** [alelievr/NodeGraphProcessor#75] opened 2020-07-26 19:29 UTC
On more complex nodes, it can become very hard to see, which port receives which value. Any plans (or a workaround) to enable this (see this screenshot from the unity forum https://forum.unity.com/attachments/upload_2018-1-18_21-14-48-png.263065/)

**Comment by alelievr** [comment] 2020-07-27 10:01
Hello, I believe this is a duplicate of https://github.com/alelievr/NodeGraphProcessor/issues/65

**Comment by alelievr** [comment] 2020-09-07 21:58
#65 is resolved so this issue follows :) 
You can now use [ShowAsDrawer] attribute on input fields to show a small drawer beside the port (like in SG)

**Closed by alelievr** 2020-09-07 21:58 UTC
Labels: duplicate
